### ISSUE TITLE
Option for Repeating Event

### ISSUE THREAD

**Issue by ryanvade** [erick2red/calendar-docs#2]
Will GNOME Calender have an option in the future to make events Repeating? So maybe set the day as Monday, Tuesday, and Wendesday of the week from the first of one month to the 3 of another or something like that? 

Also, is there a better place for feature requests?

Great work by the way.

**Comment by GeorgesStavracas** [comment]
We're working on it for 3.18 release. We're waiting for the lead designer of Calendar to come up with an elegant & effective solution, and then we'll implement it on Calendar.

**Comment by ryanvade** [comment]
Awesome!! I can't wait to see that.
